In [200]:
import numpy as np
import pandas as pd
from scipy.linalg import solve
from scipy.linalg import lstsq
import random

In [189]:
#solution with method of simple iterations
def SimIt(A,b,eps):
    number=len(A)
    alpha=np.array([[0.0 for j in range(number)] for i in range(number)])
    beta=np.array([0.0 for j in range(number)])
    for i in range(number):
        beta[i]= b[i]/A[i,i]
        for j in range(number):
            if i!=j:
                alpha[i,j]=-A[i,j]/A[i,i]
    itcount=1
    x_1=alpha.dot(beta)+beta
    x=np.copy(beta)
    while itcount<999 and np.linalg.norm((x_1-x),ord=1)>eps:
        x=np.copy(x_1)
        x_1=alpha.dot(x)+beta
        itcount=itcount+1
    x=np.copy(x_1)
    x_1=alpha.dot(x)+beta
    itcount=itcount+1
    return x_1,itcount

In [220]:
#solution with Zeidel method
def Zeid(A,b,eps):
    number = len(A)
    L=np.array([[0.0 for j in range(number)] for i in range(number)])
    D=np.array([[0.0 for j in range(number)] for i in range(number)])
    R=np.array([[0.0 for j in range(number)] for i in range(number)])
    for i in range(number):
        for j in range(number):
            if i==j:
                D[i,j]=A[i,j]
            elif i>j:
                L[i,j]=A[i,j]
            else:
                R[i,j]=A[i,j]
    alpha=-np.linalg.inv(D+L).dot(R)
    beta=np.linalg.inv(D+L).dot(b)
    itcount=1
    x_1=alpha.dot(beta)+beta
    x=np.copy(beta)
    while itcount<999 and np.linalg.norm((x_1-x),ord=1)>eps:
        x=np.copy(x_1)
        x_1=alpha.dot(x)+beta
        itcount=itcount+1
    x=np.copy(x_1)
    x_1=alpha.dot(x)+beta
    itcount=itcount+1
    return x_1,itcount

In [221]:
#bad conditioned
a = np.array([[1,0.99],[0.99,0.98]])
b=np.array([-0.393, -0.389])
x0=solve(a,b)
print(a)
print(x0)

[[1.   0.99]
 [0.99 0.98]]
[ 0.3 -0.7]


In [226]:
data = {'epsilon':[],'iterations SI': [],'||x-x~|| SI':[],'iterations Z': [],'||x-x~|| Z':[]}
df = pd.DataFrame(data)
for i in range(4,11):
    eps=10**(-i)
    res=SimIt(a,b,eps)
    rez=Zeid(a,b,eps)
    f=res[0]-x0
    fz=rez[0]-x0
    new_row={'epsilon':eps,'iterations SI': res[1],'||x-x~|| SI':np.linalg.norm(f,ord=1),'iterations Z': rez[1],'||x-x~|| Z':np.linalg.norm(f,ord=1)}
    df=df.append(new_row,ignore_index=True)
df

epsilon  iterations SI  ||x-x~|| SI  iterations Z  ||x-x~|| Z
0  1.000000e-04         1000.0     1.048197        1000.0    1.048197
1  1.000000e-05         1000.0     1.048197        1000.0    1.048197
2  1.000000e-06         1000.0     1.048197        1000.0    1.048197
3  1.000000e-07         1000.0     1.048197        1000.0    1.048197
4  1.000000e-08         1000.0     1.048197        1000.0    1.048197
5  1.000000e-09         1000.0     1.048197        1000.0    1.048197
6  1.000000e-10         1000.0     1.048197        1000.0    1.048197

In [228]:
#hilbert small
number=2
a = np.array([[0.0 for j in range(number)] for i in range(number)])
for i in range (number):
    for j in range(number):
        a[i,j]=1/(i+j+1)
b=np.array([1 for k in range(number)])
x0=lstsq(a,b)
print(a)
print(x0[0])

[[1.         0.5       ]
 [0.5        0.33333333]]
[-2.  6.]


In [229]:
data = {'epsilon':[],'iterations SI': [],'||x-x~|| SI':[],'iterations Z': [],'||x-x~|| Z':[]}
df = pd.DataFrame(data)
for i in range(4,11):
    eps=10**(-i)
    res=SimIt(a,b,eps)
    rez=Zeid(a,b,eps)
    f=res[0]-x0[0]
    fz=rez[0]-x0[0]
    new_row={'epsilon':eps,'iterations SI': res[1],'||x-x~|| SI':np.linalg.norm(f,ord=1),'iterations Z': rez[1],'||x-x~|| Z':np.linalg.norm(f,ord=1)}
    df=df.append(new_row,ignore_index=True)
df

epsilon  iterations SI   ||x-x~|| SI  iterations Z    ||x-x~|| Z
0  1.000000e-04           74.0  1.430270e-04          37.0  1.430270e-04
1  1.000000e-05           90.0  1.431885e-05          45.0  1.431885e-05
2  1.000000e-06          106.0  1.433502e-06          53.0  1.433502e-06
3  1.000000e-07          122.0  1.435120e-07          61.0  1.435120e-07
4  1.000000e-08          138.0  1.436741e-08          69.0  1.436741e-08
5  1.000000e-09          154.0  1.438360e-09          77.0  1.438360e-09
6  1.000000e-10          170.0  1.439961e-10          85.0  1.439961e-10

In [230]:
#diagonal
a = np.array([[30.4,0,0],[0,40.8,0],[0,0,60.5]])
b=np.array([6, 5,1])
x0=solve(a,b)
print(a)
print(x0)

[[30.4  0.   0. ]
 [ 0.  40.8  0. ]
 [ 0.   0.  60.5]]
[0.19736842 0.12254902 0.01652893]


In [231]:
data = {'epsilon':[],'iterations SI': [],'||x-x~|| SI':[],'iterations Z': [],'||x-x~|| Z':[]}
df = pd.DataFrame(data)
for i in range(4,11):
    eps=10**(-i)
    res=SimIt(a,b,eps)
    rez=Zeid(a,b,eps)
    f=res[0]-x0
    fz=rez[0]-x0
    new_row={'epsilon':eps,'iterations SI': res[1],'||x-x~|| SI':np.linalg.norm(f,ord=1),'iterations Z': rez[1],'||x-x~|| Z':np.linalg.norm(f,ord=1)}
    df=df.append(new_row,ignore_index=True)
df

epsilon  iterations SI  ||x-x~|| SI  iterations Z  ||x-x~|| Z
0  1.000000e-04            2.0          0.0           2.0         0.0
1  1.000000e-05            2.0          0.0           2.0         0.0
2  1.000000e-06            2.0          0.0           2.0         0.0
3  1.000000e-07            2.0          0.0           2.0         0.0
4  1.000000e-08            2.0          0.0           2.0         0.0
5  1.000000e-09            2.0          0.0           2.0         0.0
6  1.000000e-10            2.0          0.0           2.0         0.0

In [232]:
#tridiagonal
number=4
a = np.array([[4,2,0,0],[2,5,2,0],[0,2,6,2],[0,0,2,7]])
b=np.array([1 for k in range(number)])
x0=solve(a,b)
print(a)
print(x0)

[[4 2 0 0]
 [2 5 2 0]
 [0 2 6 2]
 [0 0 2 7]]
[0.21370968 0.07258065 0.10483871 0.11290323]


In [233]:
data = {'epsilon':[],'iterations SI': [],'||x-x~|| SI':[],'iterations Z': [],'||x-x~|| Z':[]}
df = pd.DataFrame(data)
for i in range(4,11):
    eps=10**(-i)
    res=SimIt(a,b,eps)
    rez=Zeid(a,b,eps)
    f=res[0]-x0
    fz=rez[0]-x0
    new_row={'epsilon':eps,'iterations SI': res[1],'||x-x~|| SI':np.linalg.norm(f,ord=1),'iterations Z': rez[1],'||x-x~|| Z':np.linalg.norm(f,ord=1)}
    df=df.append(new_row,ignore_index=True)
df

epsilon  iterations SI   ||x-x~|| SI  iterations Z    ||x-x~|| Z
0  1.000000e-04           20.0  1.592476e-05           9.0  1.592476e-05
1  1.000000e-05           24.0  2.277906e-06          11.0  2.277906e-06
2  1.000000e-06           29.0  2.087710e-07          13.0  2.087710e-07
3  1.000000e-07           34.0  1.762761e-08          16.0  1.762761e-08
4  1.000000e-08           39.0  1.615577e-09          18.0  1.615577e-09
5  1.000000e-09           43.0  2.310951e-10          21.0  2.310951e-10
6  1.000000e-10           48.0  1.951259e-11          23.0  1.951259e-11

In [234]:
#very bad
a = np.array([[1.2969, 0.8648],[0.2161,0.1441]])
b=np.array([-0.393, -0.389])
x0=solve(a,b)
print(a)
print(x0)

[[1.2969 0.8648]
 [0.2161 0.1441]]
[ 27977590.04349676 -41956680.06523005]


In [235]:
data = {'epsilon':[],'iterations SI': [],'||x-x~|| SI':[],'iterations Z': [],'||x-x~|| Z':[]}
df = pd.DataFrame(data)
for i in range(4,11):
    eps=10**(-i)
    res=SimIt(a,b,eps)
    rez=Zeid(a,b,eps)
    f=res[0]-x0
    fz=rez[0]-x0
    new_row={'epsilon':eps,'iterations SI': res[1],'||x-x~|| SI':np.linalg.norm(f,ord=1),'iterations Z': rez[1],'||x-x~|| Z':np.linalg.norm(f,ord=1)}
    df=df.append(new_row,ignore_index=True)
df

epsilon  iterations SI   ||x-x~|| SI  iterations Z    ||x-x~|| Z
0  1.000000e-04         1000.0  6.993240e+07        1000.0  6.993240e+07
1  1.000000e-05         1000.0  6.993240e+07        1000.0  6.993240e+07
2  1.000000e-06         1000.0  6.993240e+07        1000.0  6.993240e+07
3  1.000000e-07         1000.0  6.993240e+07        1000.0  6.993240e+07
4  1.000000e-08         1000.0  6.993240e+07        1000.0  6.993240e+07
5  1.000000e-09         1000.0  6.993240e+07        1000.0  6.993240e+07
6  1.000000e-10         1000.0  6.993240e+07        1000.0  6.993240e+07