In [38]:
import numpy as np
import pandas as pd
from scipy.linalg import solve

In [48]:
def PowMax(A,x0,eps):
    x_1=A.dot(x0)
    xpast=np.copy(x0)
    itcount=1
    valpast=x_1[0]/xpast[0]
    xpast=np.copy(x_1)
    x_1=A.dot(x_1)
    val=x_1[0]/xpast[0]
    while itcount<999 and abs(valpast-val)>eps:
        valpast=np.copy(val)
        xpast=np.copy(x_1)
        x_1=A.dot(x_1)
        val=x_1[0]/xpast[0]
        itcount=itcount+1
    valpast=np.copy(val)
    xpast=np.copy(x_1)
    x_1=A.dot(x_1)
    val=x_1[0]/xpast[0]
    itcount=itcount+1
    
    return abs(val),itcount

In [49]:
def ScaMax(A,x0,eps):
    x_1=A.dot(x0)
    xpast=np.copy(x0)
    AT=A.T
    itcount=1
    y_1=AT.dot(xpast)
    valpast=x_1.dot(y_1)/xpast.dot(x0)
    xpast=np.copy(x_1)
    x_1=A.dot(x_1)
    y_1=AT.dot(y_1)
    val=x_1.dot(y_1)/xpast.dot(y_1)
    while itcount<999 and abs(valpast-val)>eps:
        valpast=np.copy(val)
        xpast=np.copy(x_1)
        x_1=A.dot(x_1)
        y_1=AT.dot(y_1)
        val=x_1.dot(y_1)/xpast.dot(y_1)
        itcount=itcount+1
    valpast=np.copy(val)
    xpast=np.copy(x_1)
    x_1=A.dot(x_1)
    y_1=AT.dot(y_1)
    val=x_1.dot(y_1)/xpast.dot(y_1)
    itcount=itcount+1
    return abs(val), itcount

In [50]:
#diagonal
number=4
a = np.array([[4,2,0,0],[2,5,2,0],[0,2,6,2],[0,0,2,7]])
x0=np.array([k+1 for k in range(number)])
a

array([[4, 2, 0, 0],
       [2, 5, 2, 0],
       [0, 2, 6, 2],
       [0, 0, 2, 7]])

In [51]:
data = {'epsilon':[],'iterations PM': [],'||x-x~|| PM':[],'iterations SM': [],'||x-x~|| SM':[]}
df = pd.DataFrame(data)
eig=np.linalg.eig(a)

for number in range(2,7):
    eps=10**(-number)
    res=PowMax(a,x0,eps)
    rez=ScaMax(a,x0,eps)
    f=max(eig[0])-res[0]
    f1=max(eig[0])-rez[0]
    new_row={'epsilon':eps,'iterations PM': res[1],'||x-x~|| PM':abs(f),'iterations SM': rez[1],'||x-x~|| SM':abs(f1)}
    df=df.append(new_row,ignore_index=True)
df

epsilon  iterations PM  ||x-x~|| PM  iterations SM  ||x-x~|| SM
0  0.010000            7.0     0.058580            3.0     0.002314
1  0.001000          888.0     7.392671         1000.0     7.883169
2  0.000100         1000.0     7.358182         1000.0     7.883169
3  0.000010         1000.0     7.358182         1000.0     7.883169
4  0.000001         1000.0     7.358182         1000.0     7.883169

In [52]:
#hilbert matrix n=700
number=700
a = np.array([[0.0 for j in range(number)] for i in range(number)])
for i in range (number):
    for j in range(number):
        a[i][j]=1/(i+j+1)
x0=np.array([1/(k+1) for k in range(number)])


In [53]:
data = {'epsilon':[],'iterations PM': [],'||x-x~|| PM':[],'iterations SM': [],'||x-x~|| SM':[]}
df = pd.DataFrame(data)
eig=np.linalg.eig(a)

for number in range(2,7):
    eps=10**(-number)
    res=PowMax(a,x0,eps)
    rez=ScaMax(a,x0,eps)
    f=max(eig[0])-res[0]
    f1=max(eig[0])-rez[0]
    new_row={'epsilon':eps,'iterations PM': res[1],'||x-x~|| PM':abs(f),'iterations SM': rez[1],'||x-x~|| SM':abs(f1)}
    df=df.append(new_row,ignore_index=True)
df

epsilon  iterations PM   ||x-x~|| PM  iterations SM   ||x-x~|| SM
0  0.010000            8.0  3.631118e-03            5.0  2.118520e-04
1  0.001000           11.0  4.312638e-04            6.0  5.111135e-05
2  0.000100           15.0  2.510389e-05            8.0  2.974354e-06
3  0.000010           18.0  2.974354e-06            9.0  7.175014e-07
4  0.000001           21.0  3.524013e-07           11.0  4.175241e-08

In [54]:
#hilbert matrix n=4
number=4
a = np.array([[0.0 for j in range(number)] for i in range(number)])
for i in range (number):
    for j in range(number):
        a[i][j]=1/(i+j+1)
x0=np.array([1/(k+1) for k in range(number)])
a

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.25      , 0.2       , 0.16666667, 0.14285714]])

In [55]:
data = {'epsilon':[],'iterations PM': [],'||x-x~|| PM':[],'iterations SM': [],'||x-x~|| SM':[]}
df = pd.DataFrame(data)
eig=np.linalg.eig(a)

for number in range(2,7):
    eps=10**(-number)
    res=PowMax(a,x0,eps)
    rez=ScaMax(a,x0,eps)
    f=max(eig[0])-res[0]
    f1=max(eig[0])-rez[0]
    new_row={'epsilon':eps,'iterations PM': res[1],'||x-x~|| PM':abs(f),'iterations SM': rez[1],'||x-x~|| SM':abs(f1)}
    df=df.append(new_row,ignore_index=True)
df

epsilon  iterations PM   ||x-x~|| PM  iterations SM   ||x-x~|| SM
0  0.010000            3.0  1.159820e-04            3.0  2.113046e-09
1  0.001000            4.0  1.307736e-05            3.0  2.113046e-09
2  0.000100            6.0  1.662328e-07            3.0  2.113046e-09
3  0.000010            7.0  1.874187e-08            4.0  2.685896e-11
4  0.000001            8.0  2.113046e-09            4.0  2.685896e-11

In [56]:
number=2
a = np.array([[-401.98, 200.34],[1202.04,-602.32]])
x0=np.array([1/(k+1) for k in range(number)])
a

array([[-401.98,  200.34],
       [1202.04, -602.32]])

In [57]:
data = {'epsilon':[],'iterations PM': [],'||x-x~|| PM':[],'iterations SM': [],'||x-x~|| SM':[]}
df = pd.DataFrame(data)
eig=np.linalg.eig(a)

for number in range(2,7):
    eps=10**(-number)
    res=PowMax(a,x0,eps)
    rez=ScaMax(a,x0,eps)
    f=max(eig[0])-res[0]
    f1=max(eig[0])-rez[0]
    new_row={'epsilon':eps,'iterations PM': res[1],'||x-x~|| PM':abs(f),'iterations SM': rez[1],'||x-x~|| SM':abs(f1)}
    df=df.append(new_row,ignore_index=True)
df

epsilon  iterations PM  ||x-x~|| PM  iterations SM  ||x-x~|| SM
0  0.010000            4.0       1004.3            3.0       1004.3
1  0.001000            5.0       1004.3            3.0       1004.3
2  0.000100            5.0       1004.3            3.0       1004.3
3  0.000010            5.0       1004.3            4.0       1004.3
4  0.000001            6.0       1004.3            4.0       1004.3

In [58]:
number=2
a = np.array([[1,0.99],[0.99,0.98]])
x0=np.array([1/(k+1) for k in range(number)])
a

array([[1.  , 0.99],
       [0.99, 0.98]])

In [59]:
data = {'epsilon':[],'iterations PM': [],'||x-x~|| PM':[],'iterations SM': [],'||x-x~|| SM':[]}
df = pd.DataFrame(data)
eig=np.linalg.eig(a)

for number in range(2,7):
    eps=10**(-number)
    res=PowMax(a,x0,eps)
    rez=ScaMax(a,x0,eps)
    f=max(eig[0])-res[0]
    f1=max(eig[0])-rez[0]
    new_row={'epsilon':eps,'iterations PM': res[1],'||x-x~|| PM':abs(f),'iterations SM': rez[1],'||x-x~|| SM':abs(f1)}
    df=df.append(new_row,ignore_index=True)
df

epsilon  iterations PM   ||x-x~|| PM  iterations SM  ||x-x~|| SM
0  0.010000            3.0  1.043610e-14            3.0          0.0
1  0.001000            3.0  1.043610e-14            3.0          0.0
2  0.000100            3.0  1.043610e-14            3.0          0.0
3  0.000010            4.0  0.000000e+00            3.0          0.0
4  0.000001            4.0  0.000000e+00            3.0          0.0